CREATE TABLE `unban_member` (                           
  `member_id` int(10) unsigned NOT NULL auto_increment,
  `category_id` int(10) unsigned default NULL,
  `suid` int(12) default '0',
  `uid` int(12) default '0',
  `uname` varchar(64) default NULL,
  `email` varchar(255) default NULL,
  `ip4` varchar(255) default NULL,
  `ip6` tinytext,
  `long` varchar(120) default NULL,
  `proxy-ip4` varchar(255) default NULL,
  `proxy-ip6` tinytext,
  `network-addy` varchar(255) default NULL,
  `mac-addy` varchar(255) default NULL,
  `country-code` varchar(3) default NULL,
  `country-name` varchar(128) default NULL,
  `region-name` varchar(128) default NULL,
  `city-name` varchar(128) default NULL,
  `postcode` varchar(15) default NULL,
  `latitude` decimal(5,5) default '0.00000',
  `longitude` decimal(5,5) default '0.00000',
  `card-number` varchar(42) default '',
  `card-number-parts` mediumtext,
  `card-type` varchar(96) default '',
  `card-expire-month` tinyint(2) default '0',
  `card-expire-year` tinyint(4) default '0',
  `card-country-use` varchar(32) default '',
  `card-country-collected` varchar(32) default '',
  `card-country-shipped` varchar(32) default '',
  `card-shipping-to` mediumtext,
  `card-shipping-from` mediumtext,
  `timezone` varchar(6) default '00:00',
  `tags` varchar(255) default '',
  `made` int(12) default '0',
  PRIMARY KEY  (`member_id`),
  KEY `SEARCH` (`uid`,`suid`,`category_id`,`uname`(15),`ip4`(15),`ip6`(64),`country-code`,`postcode`,`latitude`,`longitude`,`timezone`),
  KEY `CARDFRAUD` (`category_id`,`ip4`(12),`card-number`(15),`card-type`(15),`card-expire-month`,`card-expire-year`,`card-country-use`(19),`card-country-collected`(19),`card-country-shipped`(19),`latitude`,`longitude`,`timezone`)                            
) ENGINE=INNODB ;